# Generated by Django 3.0.5 on 2020-04-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200428_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': '採取データ', 'verbose_name_plural': '採取データ'},
        ),
    ]
